name = "helphome-api"
main = "src/api/index.ts"
compatibility_date = "2025-09-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "f9dfbabe72104e969a7caa16fdf75769"

[dev]
port = 8787