name = "helphome-api"
main = "src/api/index.ts"
compatibility_date = "2026-09-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "local"

[dev]
local = true
port = 8787

workers_dev = true
